### ISSUE TITLE
How to convert received data to variables?

### ISSUE THREAD

**Issue by adrianzhang** [jesobreira/TCPServerUDF#1]
Hi Jeso,

Thanks a lot for so amazing UDF, I use it to create a 'network ready' function. details as below:
There is a functional AU3 script that help to do normal Windows tasks. And I want it to be a network service so that I can operate from remote machine.

Basically I send query from remote machine like `curl -d "user=admin&password=123" http://au3machineIP`, and on host running AU3 script I can see  user and password in $sData when using `func received($iSocket, $sIP, $sData, $sParam)`

Problem is, how to process $sData so that value in it can be transfer to local variables like $username=, $password=

I Googled and searched forum a lot, but no clue how to realize that. It is appreciate for any help.

Adrian

**Comment by adrianzhang** [comment]
Sorry, I finally find a sample case and do it well.
Refer to https://www.autoitscript.com/forum/topic/187263-split-a-multi-line-string-into-separate-variables/
answer from Subz
```
$sString = ""
$sString &= "CommonShell Command Line Scanner Lite (VSCORE.15.5.0.3960)" & @LF
$sString &= "    Engine version: 5800.7501" & @LF
$sString &= "    DAT version:    8450.0" & @LF
$sString &= "    Time required:  15 milliseconds" & @LF

$aString = StringSplit($sString, @LF)
For $i = 1 To $aString[0]
    If StringInStr($aString[$i], "DAT Version:") Then $sDATVersion = StringStripWS(StringReplace($aString[$i], "DAT Version:", ""), 8)
Next
ConsoleWrite($sDATVersion & @CRLF)
```

**Comment by jesobreira** [comment]
Hello!

If you want to parse the key=value format, the ParseStr function will help you: https://www.autoitscript.com/forum/topic/188052-phps-parse_url-and-parse_str-ported-to-autoit3/
